root = "."
tmp_dir = "tmp"

[build]
  bin = "./tmp/openscanner"
  cmd = "go build -o ./tmp/openscanner ./cmd/server"
  full_bin = "./tmp/openscanner --recordings-dir ../data/recordings --db-file ../data/openscanner.db"
  delay = 1000
  exclude_dir = ["tmp", "vendor", "testdata", "migrations", "sqlc"]
  exclude_regex = ["_test\\.go$"]
  include_dir = ["cmd", "internal"]
  include_ext = ["go"]
  kill_delay = "0s"
  send_interrupt = false
  stop_on_error = true

[log]
  time = false

[misc]
  clean_on_exit = true
