// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: accesses.sql

package db

import (
	"context"
	"database/sql"
)

const createAccess = `-- name: CreateAccess :one
INSERT INTO accesses (
    code,
    ident,
    expiration,
    "limit",
    systems_json,
    "order"
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6
) RETURNING id
`

type CreateAccessParams struct {
	Code        string         `db:"code" json:"code"`
	Ident       sql.NullString `db:"ident" json:"ident"`
	Expiration  sql.NullInt64  `db:"expiration" json:"expiration"`
	Limit       sql.NullInt64  `db:"limit" json:"limit"`
	SystemsJson sql.NullString `db:"systems_json" json:"systems_json"`
	Order       int64          `db:"order" json:"order"`
}

func (q *Queries) CreateAccess(ctx context.Context, arg CreateAccessParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createAccess,
		arg.Code,
		arg.Ident,
		arg.Expiration,
		arg.Limit,
		arg.SystemsJson,
		arg.Order,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteAccess = `-- name: DeleteAccess :exec
DELETE FROM accesses WHERE id = ?
`

func (q *Queries) DeleteAccess(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteAccess, id)
	return err
}

const getAccess = `-- name: GetAccess :one
SELECT id, code, ident, expiration, "limit", systems_json, "order" FROM accesses WHERE id = ? LIMIT 1
`

func (q *Queries) GetAccess(ctx context.Context, id int64) (Access, error) {
	row := q.db.QueryRowContext(ctx, getAccess, id)
	var i Access
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Ident,
		&i.Expiration,
		&i.Limit,
		&i.SystemsJson,
		&i.Order,
	)
	return i, err
}

const listAccesses = `-- name: ListAccesses :many
SELECT id, code, ident, expiration, "limit", systems_json, "order" FROM accesses ORDER BY "order" ASC, id ASC
`

func (q *Queries) ListAccesses(ctx context.Context) ([]Access, error) {
	rows, err := q.db.QueryContext(ctx, listAccesses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Access{}
	for rows.Next() {
		var i Access
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Ident,
			&i.Expiration,
			&i.Limit,
			&i.SystemsJson,
			&i.Order,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccess = `-- name: UpdateAccess :exec
UPDATE accesses SET
    code         = ?1,
    ident        = ?2,
    expiration   = ?3,
    "limit"      = ?4,
    systems_json = ?5,
    "order"      = ?6
WHERE id = ?7
`

type UpdateAccessParams struct {
	Code        string         `db:"code" json:"code"`
	Ident       sql.NullString `db:"ident" json:"ident"`
	Expiration  sql.NullInt64  `db:"expiration" json:"expiration"`
	Limit       sql.NullInt64  `db:"limit" json:"limit"`
	SystemsJson sql.NullString `db:"systems_json" json:"systems_json"`
	Order       int64          `db:"order" json:"order"`
	ID          int64          `db:"id" json:"id"`
}

func (q *Queries) UpdateAccess(ctx context.Context, arg UpdateAccessParams) error {
	_, err := q.db.ExecContext(ctx, updateAccess,
		arg.Code,
		arg.Ident,
		arg.Expiration,
		arg.Limit,
		arg.SystemsJson,
		arg.Order,
		arg.ID,
	)
	return err
}
