// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: activity.sql

package db

import (
	"context"
	"database/sql"
)

const getActivityStats = `-- name: GetActivityStats :one
SELECT
    (SELECT COUNT(*) FROM calls c1 WHERE c1.date_time >= ?1) AS calls_today,
    (SELECT COUNT(*) FROM calls c2 WHERE c2.date_time >= ?2) AS calls_this_week,
    (SELECT COUNT(*) FROM calls) AS calls_total
`

type GetActivityStatsParams struct {
	TodayStart int64 `db:"today_start" json:"today_start"`
	WeekStart  int64 `db:"week_start" json:"week_start"`
}

type GetActivityStatsRow struct {
	CallsToday    int64 `db:"calls_today" json:"calls_today"`
	CallsThisWeek int64 `db:"calls_this_week" json:"calls_this_week"`
	CallsTotal    int64 `db:"calls_total" json:"calls_total"`
}

// Returns aggregate stats: today's calls, this week's calls, total calls.
func (q *Queries) GetActivityStats(ctx context.Context, arg GetActivityStatsParams) (GetActivityStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getActivityStats, arg.TodayStart, arg.WeekStart)
	var i GetActivityStatsRow
	err := row.Scan(&i.CallsToday, &i.CallsThisWeek, &i.CallsTotal)
	return i, err
}

const getCallsPerHour = `-- name: GetCallsPerHour :many
SELECT
    (date_time / 3600) * 3600 AS hour_bucket,
    COUNT(*) AS call_count
FROM calls
WHERE date_time >= ?
GROUP BY hour_bucket
ORDER BY hour_bucket ASC
`

type GetCallsPerHourRow struct {
	HourBucket int64 `db:"hour_bucket" json:"hour_bucket"`
	CallCount  int64 `db:"call_count" json:"call_count"`
}

// Returns call count per hour for the last 24 hours (24 rows, one per hour bucket).
func (q *Queries) GetCallsPerHour(ctx context.Context, dateTime int64) ([]GetCallsPerHourRow, error) {
	rows, err := q.db.QueryContext(ctx, getCallsPerHour, dateTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCallsPerHourRow{}
	for rows.Next() {
		var i GetCallsPerHourRow
		if err := rows.Scan(&i.HourBucket, &i.CallCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopTalkgroups = `-- name: GetTopTalkgroups :many
SELECT
    c.talkgroup_id,
    t.label AS talkgroup_label,
    t.name AS talkgroup_name,
    s.label AS system_label,
    COUNT(*) AS call_count
FROM calls c
LEFT JOIN talkgroups t ON t.id = c.talkgroup_id
LEFT JOIN systems s ON s.id = c.system_id
WHERE c.date_time >= ?
GROUP BY c.talkgroup_id
ORDER BY call_count DESC
LIMIT ?
`

type GetTopTalkgroupsParams struct {
	DateTime int64 `db:"date_time" json:"date_time"`
	Limit    int64 `db:"limit" json:"limit"`
}

type GetTopTalkgroupsRow struct {
	TalkgroupID    sql.NullInt64  `db:"talkgroup_id" json:"talkgroup_id"`
	TalkgroupLabel sql.NullString `db:"talkgroup_label" json:"talkgroup_label"`
	TalkgroupName  sql.NullString `db:"talkgroup_name" json:"talkgroup_name"`
	SystemLabel    sql.NullString `db:"system_label" json:"system_label"`
	CallCount      int64          `db:"call_count" json:"call_count"`
}

// Returns top N busiest talkgroups (by call count) in a time range.
func (q *Queries) GetTopTalkgroups(ctx context.Context, arg GetTopTalkgroupsParams) ([]GetTopTalkgroupsRow, error) {
	rows, err := q.db.QueryContext(ctx, getTopTalkgroups, arg.DateTime, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTopTalkgroupsRow{}
	for rows.Next() {
		var i GetTopTalkgroupsRow
		if err := rows.Scan(
			&i.TalkgroupID,
			&i.TalkgroupLabel,
			&i.TalkgroupName,
			&i.SystemLabel,
			&i.CallCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
