// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: api_keys.sql

package db

import (
	"context"
	"database/sql"
)

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (
    key,
    ident,
    disabled,
    systems_json,
    "order"
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5
) RETURNING id
`

type CreateAPIKeyParams struct {
	Key         string         `db:"key" json:"key"`
	Ident       sql.NullString `db:"ident" json:"ident"`
	Disabled    int64          `db:"disabled" json:"disabled"`
	SystemsJson sql.NullString `db:"systems_json" json:"systems_json"`
	Order       int64          `db:"order" json:"order"`
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createAPIKey,
		arg.Key,
		arg.Ident,
		arg.Disabled,
		arg.SystemsJson,
		arg.Order,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteAPIKey = `-- name: DeleteAPIKey :exec
DELETE FROM api_keys WHERE id = ?
`

func (q *Queries) DeleteAPIKey(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteAPIKey, id)
	return err
}

const getAPIKey = `-- name: GetAPIKey :one
SELECT id, "key", ident, disabled, systems_json, "order" FROM api_keys WHERE id = ? LIMIT 1
`

func (q *Queries) GetAPIKey(ctx context.Context, id int64) (ApiKey, error) {
	row := q.db.QueryRowContext(ctx, getAPIKey, id)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Ident,
		&i.Disabled,
		&i.SystemsJson,
		&i.Order,
	)
	return i, err
}

const getAPIKeyByKey = `-- name: GetAPIKeyByKey :one
SELECT id, "key", ident, disabled, systems_json, "order" FROM api_keys WHERE key = ? LIMIT 1
`

func (q *Queries) GetAPIKeyByKey(ctx context.Context, key string) (ApiKey, error) {
	row := q.db.QueryRowContext(ctx, getAPIKeyByKey, key)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Ident,
		&i.Disabled,
		&i.SystemsJson,
		&i.Order,
	)
	return i, err
}

const listAPIKeys = `-- name: ListAPIKeys :many
SELECT id, "key", ident, disabled, systems_json, "order" FROM api_keys ORDER BY "order" ASC, id ASC
`

func (q *Queries) ListAPIKeys(ctx context.Context) ([]ApiKey, error) {
	rows, err := q.db.QueryContext(ctx, listAPIKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiKey{}
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Ident,
			&i.Disabled,
			&i.SystemsJson,
			&i.Order,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAPIKey = `-- name: UpdateAPIKey :exec
UPDATE api_keys SET
    key          = ?1,
    ident        = ?2,
    disabled     = ?3,
    systems_json = ?4,
    "order"      = ?5
WHERE id = ?6
`

type UpdateAPIKeyParams struct {
	Key         string         `db:"key" json:"key"`
	Ident       sql.NullString `db:"ident" json:"ident"`
	Disabled    int64          `db:"disabled" json:"disabled"`
	SystemsJson sql.NullString `db:"systems_json" json:"systems_json"`
	Order       int64          `db:"order" json:"order"`
	ID          int64          `db:"id" json:"id"`
}

func (q *Queries) UpdateAPIKey(ctx context.Context, arg UpdateAPIKeyParams) error {
	_, err := q.db.ExecContext(ctx, updateAPIKey,
		arg.Key,
		arg.Ident,
		arg.Disabled,
		arg.SystemsJson,
		arg.Order,
		arg.ID,
	)
	return err
}
