// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: app_state.sql

package db

import (
	"context"
)

const getAppState = `-- name: GetAppState :one
SELECT id, setup_complete FROM app_state WHERE id = 1 LIMIT 1
`

func (q *Queries) GetAppState(ctx context.Context) (AppState, error) {
	row := q.db.QueryRowContext(ctx, getAppState)
	var i AppState
	err := row.Scan(&i.ID, &i.SetupComplete)
	return i, err
}

const setSetupComplete = `-- name: SetSetupComplete :exec
UPDATE app_state SET setup_complete = ? WHERE id = 1
`

func (q *Queries) SetSetupComplete(ctx context.Context, setupComplete int64) error {
	_, err := q.db.ExecContext(ctx, setSetupComplete, setupComplete)
	return err
}
