// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: bookmarks.sql

package db

import (
	"context"
	"database/sql"
)

const createBookmark = `-- name: CreateBookmark :one
INSERT INTO bookmarks (call_id, user_id, session_id, created_at)
VALUES (?1, ?2, ?3, ?4)
RETURNING id
`

type CreateBookmarkParams struct {
	CallID    int64          `db:"call_id" json:"call_id"`
	UserID    sql.NullInt64  `db:"user_id" json:"user_id"`
	SessionID sql.NullString `db:"session_id" json:"session_id"`
	CreatedAt int64          `db:"created_at" json:"created_at"`
}

func (q *Queries) CreateBookmark(ctx context.Context, arg CreateBookmarkParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createBookmark,
		arg.CallID,
		arg.UserID,
		arg.SessionID,
		arg.CreatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteBookmark = `-- name: DeleteBookmark :exec
DELETE FROM bookmarks WHERE id = ?
`

func (q *Queries) DeleteBookmark(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteBookmark, id)
	return err
}

const deleteBookmarkByCallAndUser = `-- name: DeleteBookmarkByCallAndUser :exec
DELETE FROM bookmarks WHERE call_id = ? AND user_id = ?
`

type DeleteBookmarkByCallAndUserParams struct {
	CallID int64         `db:"call_id" json:"call_id"`
	UserID sql.NullInt64 `db:"user_id" json:"user_id"`
}

func (q *Queries) DeleteBookmarkByCallAndUser(ctx context.Context, arg DeleteBookmarkByCallAndUserParams) error {
	_, err := q.db.ExecContext(ctx, deleteBookmarkByCallAndUser, arg.CallID, arg.UserID)
	return err
}

const getBookmark = `-- name: GetBookmark :one
SELECT id, call_id, user_id, session_id, created_at FROM bookmarks WHERE id = ? LIMIT 1
`

func (q *Queries) GetBookmark(ctx context.Context, id int64) (Bookmark, error) {
	row := q.db.QueryRowContext(ctx, getBookmark, id)
	var i Bookmark
	err := row.Scan(
		&i.ID,
		&i.CallID,
		&i.UserID,
		&i.SessionID,
		&i.CreatedAt,
	)
	return i, err
}

const listBookmarksBySession = `-- name: ListBookmarksBySession :many
SELECT id, call_id, user_id, session_id, created_at FROM bookmarks WHERE session_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListBookmarksBySession(ctx context.Context, sessionID sql.NullString) ([]Bookmark, error) {
	rows, err := q.db.QueryContext(ctx, listBookmarksBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Bookmark{}
	for rows.Next() {
		var i Bookmark
		if err := rows.Scan(
			&i.ID,
			&i.CallID,
			&i.UserID,
			&i.SessionID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBookmarksByUser = `-- name: ListBookmarksByUser :many
SELECT id, call_id, user_id, session_id, created_at FROM bookmarks WHERE user_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListBookmarksByUser(ctx context.Context, userID sql.NullInt64) ([]Bookmark, error) {
	rows, err := q.db.QueryContext(ctx, listBookmarksByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Bookmark{}
	for rows.Next() {
		var i Bookmark
		if err := rows.Scan(
			&i.ID,
			&i.CallID,
			&i.UserID,
			&i.SessionID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
