// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: calls.sql

package db

import (
	"context"
	"database/sql"
)

const countCalls = `-- name: CountCalls :one
SELECT COUNT(*) FROM calls
`

func (q *Queries) CountCalls(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCalls)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCall = `-- name: CreateCall :one
INSERT INTO calls (
    audio_path,
    audio_name,
    audio_type,
    date_time,
    frequency,
    duration,
    source,
    sources_json,
    frequencies_json,
    patches_json,
    system_id,
    talkgroup_id
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7,
    ?8,
    ?9,
    ?10,
    ?11,
    ?12
) RETURNING id
`

type CreateCallParams struct {
	AudioPath       string         `db:"audio_path" json:"audio_path"`
	AudioName       string         `db:"audio_name" json:"audio_name"`
	AudioType       string         `db:"audio_type" json:"audio_type"`
	DateTime        int64          `db:"date_time" json:"date_time"`
	Frequency       sql.NullInt64  `db:"frequency" json:"frequency"`
	Duration        sql.NullInt64  `db:"duration" json:"duration"`
	Source          sql.NullInt64  `db:"source" json:"source"`
	SourcesJson     sql.NullString `db:"sources_json" json:"sources_json"`
	FrequenciesJson sql.NullString `db:"frequencies_json" json:"frequencies_json"`
	PatchesJson     sql.NullString `db:"patches_json" json:"patches_json"`
	SystemID        int64          `db:"system_id" json:"system_id"`
	TalkgroupID     sql.NullInt64  `db:"talkgroup_id" json:"talkgroup_id"`
}

func (q *Queries) CreateCall(ctx context.Context, arg CreateCallParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createCall,
		arg.AudioPath,
		arg.AudioName,
		arg.AudioType,
		arg.DateTime,
		arg.Frequency,
		arg.Duration,
		arg.Source,
		arg.SourcesJson,
		arg.FrequenciesJson,
		arg.PatchesJson,
		arg.SystemID,
		arg.TalkgroupID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteCall = `-- name: DeleteCall :exec
DELETE FROM calls WHERE id = ?
`

func (q *Queries) DeleteCall(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteCall, id)
	return err
}

const deleteCallBatch = `-- name: DeleteCallBatch :exec
DELETE FROM calls WHERE id = ?
`

func (q *Queries) DeleteCallBatch(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteCallBatch, id)
	return err
}

const getCall = `-- name: GetCall :one
SELECT
    c.id, c.audio_path, c.audio_name, c.audio_type, c.date_time, c.frequency, c.duration, c.source, c.sources_json, c.frequencies_json, c.patches_json, c.system_id, c.talkgroup_id,
    s.label  AS system_label,
    t.label  AS talkgroup_label,
    t.name   AS talkgroup_name
FROM calls c
LEFT JOIN systems    s ON s.id = c.system_id
LEFT JOIN talkgroups t ON t.id = c.talkgroup_id
WHERE c.id = ?
LIMIT 1
`

type GetCallRow struct {
	ID              int64          `db:"id" json:"id"`
	AudioPath       string         `db:"audio_path" json:"audio_path"`
	AudioName       string         `db:"audio_name" json:"audio_name"`
	AudioType       string         `db:"audio_type" json:"audio_type"`
	DateTime        int64          `db:"date_time" json:"date_time"`
	Frequency       sql.NullInt64  `db:"frequency" json:"frequency"`
	Duration        sql.NullInt64  `db:"duration" json:"duration"`
	Source          sql.NullInt64  `db:"source" json:"source"`
	SourcesJson     sql.NullString `db:"sources_json" json:"sources_json"`
	FrequenciesJson sql.NullString `db:"frequencies_json" json:"frequencies_json"`
	PatchesJson     sql.NullString `db:"patches_json" json:"patches_json"`
	SystemID        int64          `db:"system_id" json:"system_id"`
	TalkgroupID     sql.NullInt64  `db:"talkgroup_id" json:"talkgroup_id"`
	SystemLabel     sql.NullString `db:"system_label" json:"system_label"`
	TalkgroupLabel  sql.NullString `db:"talkgroup_label" json:"talkgroup_label"`
	TalkgroupName   sql.NullString `db:"talkgroup_name" json:"talkgroup_name"`
}

func (q *Queries) GetCall(ctx context.Context, id int64) (GetCallRow, error) {
	row := q.db.QueryRowContext(ctx, getCall, id)
	var i GetCallRow
	err := row.Scan(
		&i.ID,
		&i.AudioPath,
		&i.AudioName,
		&i.AudioType,
		&i.DateTime,
		&i.Frequency,
		&i.Duration,
		&i.Source,
		&i.SourcesJson,
		&i.FrequenciesJson,
		&i.PatchesJson,
		&i.SystemID,
		&i.TalkgroupID,
		&i.SystemLabel,
		&i.TalkgroupLabel,
		&i.TalkgroupName,
	)
	return i, err
}

const getCallIDsOlderThan = `-- name: GetCallIDsOlderThan :many
SELECT id, audio_path
FROM calls
WHERE date_time < ?
ORDER BY date_time ASC
LIMIT 500
`

type GetCallIDsOlderThanRow struct {
	ID        int64  `db:"id" json:"id"`
	AudioPath string `db:"audio_path" json:"audio_path"`
}

func (q *Queries) GetCallIDsOlderThan(ctx context.Context, dateTime int64) ([]GetCallIDsOlderThanRow, error) {
	rows, err := q.db.QueryContext(ctx, getCallIDsOlderThan, dateTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCallIDsOlderThanRow{}
	for rows.Next() {
		var i GetCallIDsOlderThanRow
		if err := rows.Scan(&i.ID, &i.AudioPath); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLastCallForTalkgroup = `-- name: GetLastCallForTalkgroup :one
SELECT c.date_time, c.duration
FROM calls c
WHERE c.system_id = ? AND c.talkgroup_id = ?
ORDER BY c.date_time DESC
LIMIT 1
`

type GetLastCallForTalkgroupParams struct {
	SystemID    int64         `db:"system_id" json:"system_id"`
	TalkgroupID sql.NullInt64 `db:"talkgroup_id" json:"talkgroup_id"`
}

type GetLastCallForTalkgroupRow struct {
	DateTime int64         `db:"date_time" json:"date_time"`
	Duration sql.NullInt64 `db:"duration" json:"duration"`
}

func (q *Queries) GetLastCallForTalkgroup(ctx context.Context, arg GetLastCallForTalkgroupParams) (GetLastCallForTalkgroupRow, error) {
	row := q.db.QueryRowContext(ctx, getLastCallForTalkgroup, arg.SystemID, arg.TalkgroupID)
	var i GetLastCallForTalkgroupRow
	err := row.Scan(&i.DateTime, &i.Duration)
	return i, err
}

const listCalls = `-- name: ListCalls :many
SELECT c.id, c.audio_path, c.audio_name, c.audio_type, c.date_time, c.frequency, c.duration, c.source, c.sources_json, c.frequencies_json, c.patches_json, c.system_id, c.talkgroup_id
FROM calls c
WHERE
    (?1    IS NULL OR c.system_id    = ?1)
    AND (?2 IS NULL OR c.talkgroup_id = ?2)
    AND (?3    IS NULL OR c.date_time    >= ?3)
    AND (?4      IS NULL OR c.date_time    <= ?4)
ORDER BY c.date_time DESC
LIMIT  ?6
OFFSET ?5
`

type ListCallsParams struct {
	SystemID    interface{}   `db:"system_id" json:"system_id"`
	TalkgroupID interface{}   `db:"talkgroup_id" json:"talkgroup_id"`
	DateFrom    interface{}   `db:"date_from" json:"date_from"`
	DateTo      interface{}   `db:"date_to" json:"date_to"`
	PageOffset  sql.NullInt64 `db:"page_offset" json:"page_offset"`
	PageSize    sql.NullInt64 `db:"page_size" json:"page_size"`
}

func (q *Queries) ListCalls(ctx context.Context, arg ListCallsParams) ([]Call, error) {
	rows, err := q.db.QueryContext(ctx, listCalls,
		arg.SystemID,
		arg.TalkgroupID,
		arg.DateFrom,
		arg.DateTo,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Call{}
	for rows.Next() {
		var i Call
		if err := rows.Scan(
			&i.ID,
			&i.AudioPath,
			&i.AudioName,
			&i.AudioType,
			&i.DateTime,
			&i.Frequency,
			&i.Duration,
			&i.Source,
			&i.SourcesJson,
			&i.FrequenciesJson,
			&i.PatchesJson,
			&i.SystemID,
			&i.TalkgroupID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneCalls = `-- name: PruneCalls :exec
DELETE FROM calls WHERE date_time < ?
`

func (q *Queries) PruneCalls(ctx context.Context, dateTime int64) error {
	_, err := q.db.ExecContext(ctx, pruneCalls, dateTime)
	return err
}
