// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: dirmonitors.sql

package db

import (
	"context"
	"database/sql"
)

const createDirMonitor = `-- name: CreateDirMonitor :one
INSERT INTO dirmonitors (
    directory,
    type,
    mask,
    extension,
    frequency,
    delay,
    delete_after,
    use_polling,
    disabled,
    system_id,
    talkgroup_id,
    "order"
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7,
    ?8,
    ?9,
    ?10,
    ?11,
    ?12
) RETURNING id
`

type CreateDirMonitorParams struct {
	Directory   string         `db:"directory" json:"directory"`
	Type        string         `db:"type" json:"type"`
	Mask        sql.NullString `db:"mask" json:"mask"`
	Extension   sql.NullString `db:"extension" json:"extension"`
	Frequency   sql.NullInt64  `db:"frequency" json:"frequency"`
	Delay       sql.NullInt64  `db:"delay" json:"delay"`
	DeleteAfter int64          `db:"delete_after" json:"delete_after"`
	UsePolling  int64          `db:"use_polling" json:"use_polling"`
	Disabled    int64          `db:"disabled" json:"disabled"`
	SystemID    sql.NullInt64  `db:"system_id" json:"system_id"`
	TalkgroupID sql.NullInt64  `db:"talkgroup_id" json:"talkgroup_id"`
	Order       int64          `db:"order" json:"order"`
}

func (q *Queries) CreateDirMonitor(ctx context.Context, arg CreateDirMonitorParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createDirMonitor,
		arg.Directory,
		arg.Type,
		arg.Mask,
		arg.Extension,
		arg.Frequency,
		arg.Delay,
		arg.DeleteAfter,
		arg.UsePolling,
		arg.Disabled,
		arg.SystemID,
		arg.TalkgroupID,
		arg.Order,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteDirMonitor = `-- name: DeleteDirMonitor :exec
DELETE FROM dirmonitors WHERE id = ?
`

func (q *Queries) DeleteDirMonitor(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteDirMonitor, id)
	return err
}

const getDirMonitor = `-- name: GetDirMonitor :one
SELECT id, directory, type, mask, extension, frequency, delay, delete_after, use_polling, disabled, system_id, talkgroup_id, "order" FROM dirmonitors WHERE id = ? LIMIT 1
`

func (q *Queries) GetDirMonitor(ctx context.Context, id int64) (Dirmonitor, error) {
	row := q.db.QueryRowContext(ctx, getDirMonitor, id)
	var i Dirmonitor
	err := row.Scan(
		&i.ID,
		&i.Directory,
		&i.Type,
		&i.Mask,
		&i.Extension,
		&i.Frequency,
		&i.Delay,
		&i.DeleteAfter,
		&i.UsePolling,
		&i.Disabled,
		&i.SystemID,
		&i.TalkgroupID,
		&i.Order,
	)
	return i, err
}

const listActiveDirMonitors = `-- name: ListActiveDirMonitors :many
SELECT id, directory, type, mask, extension, frequency, delay, delete_after, use_polling, disabled, system_id, talkgroup_id, "order" FROM dirmonitors WHERE disabled = 0 ORDER BY "order" ASC, id ASC
`

func (q *Queries) ListActiveDirMonitors(ctx context.Context) ([]Dirmonitor, error) {
	rows, err := q.db.QueryContext(ctx, listActiveDirMonitors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Dirmonitor{}
	for rows.Next() {
		var i Dirmonitor
		if err := rows.Scan(
			&i.ID,
			&i.Directory,
			&i.Type,
			&i.Mask,
			&i.Extension,
			&i.Frequency,
			&i.Delay,
			&i.DeleteAfter,
			&i.UsePolling,
			&i.Disabled,
			&i.SystemID,
			&i.TalkgroupID,
			&i.Order,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDirMonitors = `-- name: ListDirMonitors :many
SELECT id, directory, type, mask, extension, frequency, delay, delete_after, use_polling, disabled, system_id, talkgroup_id, "order" FROM dirmonitors ORDER BY "order" ASC, id ASC
`

func (q *Queries) ListDirMonitors(ctx context.Context) ([]Dirmonitor, error) {
	rows, err := q.db.QueryContext(ctx, listDirMonitors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Dirmonitor{}
	for rows.Next() {
		var i Dirmonitor
		if err := rows.Scan(
			&i.ID,
			&i.Directory,
			&i.Type,
			&i.Mask,
			&i.Extension,
			&i.Frequency,
			&i.Delay,
			&i.DeleteAfter,
			&i.UsePolling,
			&i.Disabled,
			&i.SystemID,
			&i.TalkgroupID,
			&i.Order,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDirMonitor = `-- name: UpdateDirMonitor :exec
UPDATE dirmonitors SET
    directory    = ?1,
    type         = ?2,
    mask         = ?3,
    extension    = ?4,
    frequency    = ?5,
    delay        = ?6,
    delete_after = ?7,
    use_polling  = ?8,
    disabled     = ?9,
    system_id    = ?10,
    talkgroup_id = ?11,
    "order"      = ?12
WHERE id = ?13
`

type UpdateDirMonitorParams struct {
	Directory   string         `db:"directory" json:"directory"`
	Type        string         `db:"type" json:"type"`
	Mask        sql.NullString `db:"mask" json:"mask"`
	Extension   sql.NullString `db:"extension" json:"extension"`
	Frequency   sql.NullInt64  `db:"frequency" json:"frequency"`
	Delay       sql.NullInt64  `db:"delay" json:"delay"`
	DeleteAfter int64          `db:"delete_after" json:"delete_after"`
	UsePolling  int64          `db:"use_polling" json:"use_polling"`
	Disabled    int64          `db:"disabled" json:"disabled"`
	SystemID    sql.NullInt64  `db:"system_id" json:"system_id"`
	TalkgroupID sql.NullInt64  `db:"talkgroup_id" json:"talkgroup_id"`
	Order       int64          `db:"order" json:"order"`
	ID          int64          `db:"id" json:"id"`
}

func (q *Queries) UpdateDirMonitor(ctx context.Context, arg UpdateDirMonitorParams) error {
	_, err := q.db.ExecContext(ctx, updateDirMonitor,
		arg.Directory,
		arg.Type,
		arg.Mask,
		arg.Extension,
		arg.Frequency,
		arg.Delay,
		arg.DeleteAfter,
		arg.UsePolling,
		arg.Disabled,
		arg.SystemID,
		arg.TalkgroupID,
		arg.Order,
		arg.ID,
	)
	return err
}
