// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: dirwatches.sql

package db

import (
	"context"
	"database/sql"
)

const createDirwatch = `-- name: CreateDirwatch :one
INSERT INTO dirwatches (
    directory,
    type,
    mask,
    extension,
    frequency,
    delay,
    delete_after,
    use_polling,
    disabled,
    system_id,
    talkgroup_id,
    "order"
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7,
    ?8,
    ?9,
    ?10,
    ?11,
    ?12
) RETURNING id
`

type CreateDirwatchParams struct {
	Directory   string         `db:"directory" json:"directory"`
	Type        string         `db:"type" json:"type"`
	Mask        sql.NullString `db:"mask" json:"mask"`
	Extension   sql.NullString `db:"extension" json:"extension"`
	Frequency   sql.NullInt64  `db:"frequency" json:"frequency"`
	Delay       sql.NullInt64  `db:"delay" json:"delay"`
	DeleteAfter int64          `db:"delete_after" json:"delete_after"`
	UsePolling  int64          `db:"use_polling" json:"use_polling"`
	Disabled    int64          `db:"disabled" json:"disabled"`
	SystemID    sql.NullInt64  `db:"system_id" json:"system_id"`
	TalkgroupID sql.NullInt64  `db:"talkgroup_id" json:"talkgroup_id"`
	Order       int64          `db:"order" json:"order"`
}

func (q *Queries) CreateDirwatch(ctx context.Context, arg CreateDirwatchParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createDirwatch,
		arg.Directory,
		arg.Type,
		arg.Mask,
		arg.Extension,
		arg.Frequency,
		arg.Delay,
		arg.DeleteAfter,
		arg.UsePolling,
		arg.Disabled,
		arg.SystemID,
		arg.TalkgroupID,
		arg.Order,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteDirwatch = `-- name: DeleteDirwatch :exec
DELETE FROM dirwatches WHERE id = ?
`

func (q *Queries) DeleteDirwatch(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteDirwatch, id)
	return err
}

const getDirwatch = `-- name: GetDirwatch :one
SELECT id, directory, type, mask, extension, frequency, delay, delete_after, use_polling, disabled, system_id, talkgroup_id, "order" FROM dirwatches WHERE id = ? LIMIT 1
`

func (q *Queries) GetDirwatch(ctx context.Context, id int64) (Dirwatch, error) {
	row := q.db.QueryRowContext(ctx, getDirwatch, id)
	var i Dirwatch
	err := row.Scan(
		&i.ID,
		&i.Directory,
		&i.Type,
		&i.Mask,
		&i.Extension,
		&i.Frequency,
		&i.Delay,
		&i.DeleteAfter,
		&i.UsePolling,
		&i.Disabled,
		&i.SystemID,
		&i.TalkgroupID,
		&i.Order,
	)
	return i, err
}

const listActiveDirwatches = `-- name: ListActiveDirwatches :many
SELECT id, directory, type, mask, extension, frequency, delay, delete_after, use_polling, disabled, system_id, talkgroup_id, "order" FROM dirwatches WHERE disabled = 0 ORDER BY "order" ASC, id ASC
`

func (q *Queries) ListActiveDirwatches(ctx context.Context) ([]Dirwatch, error) {
	rows, err := q.db.QueryContext(ctx, listActiveDirwatches)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Dirwatch{}
	for rows.Next() {
		var i Dirwatch
		if err := rows.Scan(
			&i.ID,
			&i.Directory,
			&i.Type,
			&i.Mask,
			&i.Extension,
			&i.Frequency,
			&i.Delay,
			&i.DeleteAfter,
			&i.UsePolling,
			&i.Disabled,
			&i.SystemID,
			&i.TalkgroupID,
			&i.Order,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDirwatches = `-- name: ListDirwatches :many
SELECT id, directory, type, mask, extension, frequency, delay, delete_after, use_polling, disabled, system_id, talkgroup_id, "order" FROM dirwatches ORDER BY "order" ASC, id ASC
`

func (q *Queries) ListDirwatches(ctx context.Context) ([]Dirwatch, error) {
	rows, err := q.db.QueryContext(ctx, listDirwatches)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Dirwatch{}
	for rows.Next() {
		var i Dirwatch
		if err := rows.Scan(
			&i.ID,
			&i.Directory,
			&i.Type,
			&i.Mask,
			&i.Extension,
			&i.Frequency,
			&i.Delay,
			&i.DeleteAfter,
			&i.UsePolling,
			&i.Disabled,
			&i.SystemID,
			&i.TalkgroupID,
			&i.Order,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDirwatch = `-- name: UpdateDirwatch :exec
UPDATE dirwatches SET
    directory    = ?1,
    type         = ?2,
    mask         = ?3,
    extension    = ?4,
    frequency    = ?5,
    delay        = ?6,
    delete_after = ?7,
    use_polling  = ?8,
    disabled     = ?9,
    system_id    = ?10,
    talkgroup_id = ?11,
    "order"      = ?12
WHERE id = ?13
`

type UpdateDirwatchParams struct {
	Directory   string         `db:"directory" json:"directory"`
	Type        string         `db:"type" json:"type"`
	Mask        sql.NullString `db:"mask" json:"mask"`
	Extension   sql.NullString `db:"extension" json:"extension"`
	Frequency   sql.NullInt64  `db:"frequency" json:"frequency"`
	Delay       sql.NullInt64  `db:"delay" json:"delay"`
	DeleteAfter int64          `db:"delete_after" json:"delete_after"`
	UsePolling  int64          `db:"use_polling" json:"use_polling"`
	Disabled    int64          `db:"disabled" json:"disabled"`
	SystemID    sql.NullInt64  `db:"system_id" json:"system_id"`
	TalkgroupID sql.NullInt64  `db:"talkgroup_id" json:"talkgroup_id"`
	Order       int64          `db:"order" json:"order"`
	ID          int64          `db:"id" json:"id"`
}

func (q *Queries) UpdateDirwatch(ctx context.Context, arg UpdateDirwatchParams) error {
	_, err := q.db.ExecContext(ctx, updateDirwatch,
		arg.Directory,
		arg.Type,
		arg.Mask,
		arg.Extension,
		arg.Frequency,
		arg.Delay,
		arg.DeleteAfter,
		arg.UsePolling,
		arg.Disabled,
		arg.SystemID,
		arg.TalkgroupID,
		arg.Order,
		arg.ID,
	)
	return err
}
