// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: downstreams.sql

package db

import (
	"context"
	"database/sql"
)

const createDownstream = `-- name: CreateDownstream :one
INSERT INTO downstreams (
    url,
    api_key,
    systems_json,
    disabled,
    "order"
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5
) RETURNING id
`

type CreateDownstreamParams struct {
	Url         string         `db:"url" json:"url"`
	ApiKey      string         `db:"api_key" json:"api_key"`
	SystemsJson sql.NullString `db:"systems_json" json:"systems_json"`
	Disabled    int64          `db:"disabled" json:"disabled"`
	Order       int64          `db:"order" json:"order"`
}

func (q *Queries) CreateDownstream(ctx context.Context, arg CreateDownstreamParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createDownstream,
		arg.Url,
		arg.ApiKey,
		arg.SystemsJson,
		arg.Disabled,
		arg.Order,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteDownstream = `-- name: DeleteDownstream :exec
DELETE FROM downstreams WHERE id = ?
`

func (q *Queries) DeleteDownstream(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteDownstream, id)
	return err
}

const getDownstream = `-- name: GetDownstream :one
SELECT id, url, api_key, systems_json, disabled, "order" FROM downstreams WHERE id = ? LIMIT 1
`

func (q *Queries) GetDownstream(ctx context.Context, id int64) (Downstream, error) {
	row := q.db.QueryRowContext(ctx, getDownstream, id)
	var i Downstream
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.ApiKey,
		&i.SystemsJson,
		&i.Disabled,
		&i.Order,
	)
	return i, err
}

const listActiveDownstreams = `-- name: ListActiveDownstreams :many
SELECT id, url, api_key, systems_json, disabled, "order" FROM downstreams WHERE disabled = 0 ORDER BY "order" ASC, id ASC
`

func (q *Queries) ListActiveDownstreams(ctx context.Context) ([]Downstream, error) {
	rows, err := q.db.QueryContext(ctx, listActiveDownstreams)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Downstream{}
	for rows.Next() {
		var i Downstream
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.ApiKey,
			&i.SystemsJson,
			&i.Disabled,
			&i.Order,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDownstreams = `-- name: ListDownstreams :many
SELECT id, url, api_key, systems_json, disabled, "order" FROM downstreams ORDER BY "order" ASC, id ASC
`

func (q *Queries) ListDownstreams(ctx context.Context) ([]Downstream, error) {
	rows, err := q.db.QueryContext(ctx, listDownstreams)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Downstream{}
	for rows.Next() {
		var i Downstream
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.ApiKey,
			&i.SystemsJson,
			&i.Disabled,
			&i.Order,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDownstream = `-- name: UpdateDownstream :exec
UPDATE downstreams SET
    url          = ?1,
    api_key      = ?2,
    systems_json = ?3,
    disabled     = ?4,
    "order"      = ?5
WHERE id = ?6
`

type UpdateDownstreamParams struct {
	Url         string         `db:"url" json:"url"`
	ApiKey      string         `db:"api_key" json:"api_key"`
	SystemsJson sql.NullString `db:"systems_json" json:"systems_json"`
	Disabled    int64          `db:"disabled" json:"disabled"`
	Order       int64          `db:"order" json:"order"`
	ID          int64          `db:"id" json:"id"`
}

func (q *Queries) UpdateDownstream(ctx context.Context, arg UpdateDownstreamParams) error {
	_, err := q.db.ExecContext(ctx, updateDownstream,
		arg.Url,
		arg.ApiKey,
		arg.SystemsJson,
		arg.Disabled,
		arg.Order,
		arg.ID,
	)
	return err
}
