// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: groups.sql

package db

import (
	"context"
)

const createGroup = `-- name: CreateGroup :one
INSERT INTO groups (label) VALUES (?1) RETURNING id
`

func (q *Queries) CreateGroup(ctx context.Context, label string) (int64, error) {
	row := q.db.QueryRowContext(ctx, createGroup, label)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteGroup = `-- name: DeleteGroup :exec
DELETE FROM groups WHERE id = ?
`

func (q *Queries) DeleteGroup(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteGroup, id)
	return err
}

const getGroup = `-- name: GetGroup :one
SELECT id, label FROM groups WHERE id = ? LIMIT 1
`

func (q *Queries) GetGroup(ctx context.Context, id int64) (Group, error) {
	row := q.db.QueryRowContext(ctx, getGroup, id)
	var i Group
	err := row.Scan(&i.ID, &i.Label)
	return i, err
}

const getGroupByLabel = `-- name: GetGroupByLabel :one
SELECT id, label FROM groups WHERE label = ? LIMIT 1
`

func (q *Queries) GetGroupByLabel(ctx context.Context, label string) (Group, error) {
	row := q.db.QueryRowContext(ctx, getGroupByLabel, label)
	var i Group
	err := row.Scan(&i.ID, &i.Label)
	return i, err
}

const listGroups = `-- name: ListGroups :many
SELECT id, label FROM groups ORDER BY label ASC
`

func (q *Queries) ListGroups(ctx context.Context) ([]Group, error) {
	rows, err := q.db.QueryContext(ctx, listGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Group{}
	for rows.Next() {
		var i Group
		if err := rows.Scan(&i.ID, &i.Label); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGroup = `-- name: UpdateGroup :exec
UPDATE groups SET label = ?1 WHERE id = ?2
`

type UpdateGroupParams struct {
	Label string `db:"label" json:"label"`
	ID    int64  `db:"id" json:"id"`
}

func (q *Queries) UpdateGroup(ctx context.Context, arg UpdateGroupParams) error {
	_, err := q.db.ExecContext(ctx, updateGroup, arg.Label, arg.ID)
	return err
}
