// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: logs.sql

package db

import (
	"context"
)

const createLog = `-- name: CreateLog :exec
INSERT INTO logs (date_time, level, message)
VALUES (?1, ?2, ?3)
`

type CreateLogParams struct {
	DateTime int64  `db:"date_time" json:"date_time"`
	Level    string `db:"level" json:"level"`
	Message  string `db:"message" json:"message"`
}

func (q *Queries) CreateLog(ctx context.Context, arg CreateLogParams) error {
	_, err := q.db.ExecContext(ctx, createLog, arg.DateTime, arg.Level, arg.Message)
	return err
}
