// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
)

type ApiKey struct {
	ID          int64          `db:"id" json:"id"`
	Key         string         `db:"key" json:"key"`
	Ident       sql.NullString `db:"ident" json:"ident"`
	Disabled    int64          `db:"disabled" json:"disabled"`
	SystemsJson sql.NullString `db:"systems_json" json:"systems_json"`
	Order       int64          `db:"order" json:"order"`
}

type AppState struct {
	ID            int64 `db:"id" json:"id"`
	SetupComplete int64 `db:"setup_complete" json:"setup_complete"`
}

type Bookmark struct {
	ID        int64          `db:"id" json:"id"`
	CallID    int64          `db:"call_id" json:"call_id"`
	UserID    sql.NullInt64  `db:"user_id" json:"user_id"`
	SessionID sql.NullString `db:"session_id" json:"session_id"`
	CreatedAt int64          `db:"created_at" json:"created_at"`
}

type Call struct {
	ID              int64          `db:"id" json:"id"`
	AudioPath       string         `db:"audio_path" json:"audio_path"`
	AudioName       string         `db:"audio_name" json:"audio_name"`
	AudioType       string         `db:"audio_type" json:"audio_type"`
	DateTime        int64          `db:"date_time" json:"date_time"`
	Frequency       sql.NullInt64  `db:"frequency" json:"frequency"`
	Duration        sql.NullInt64  `db:"duration" json:"duration"`
	Source          sql.NullInt64  `db:"source" json:"source"`
	SourcesJson     sql.NullString `db:"sources_json" json:"sources_json"`
	FrequenciesJson sql.NullString `db:"frequencies_json" json:"frequencies_json"`
	PatchesJson     sql.NullString `db:"patches_json" json:"patches_json"`
	SystemID        int64          `db:"system_id" json:"system_id"`
	TalkgroupID     sql.NullInt64  `db:"talkgroup_id" json:"talkgroup_id"`
	Site            sql.NullString `db:"site" json:"site"`
	Channel         sql.NullString `db:"channel" json:"channel"`
	Decoder         sql.NullString `db:"decoder" json:"decoder"`
}

type Dirwatch struct {
	ID          int64          `db:"id" json:"id"`
	Directory   string         `db:"directory" json:"directory"`
	Type        string         `db:"type" json:"type"`
	Mask        sql.NullString `db:"mask" json:"mask"`
	Extension   sql.NullString `db:"extension" json:"extension"`
	Frequency   sql.NullInt64  `db:"frequency" json:"frequency"`
	Delay       sql.NullInt64  `db:"delay" json:"delay"`
	DeleteAfter int64          `db:"delete_after" json:"delete_after"`
	UsePolling  int64          `db:"use_polling" json:"use_polling"`
	Disabled    int64          `db:"disabled" json:"disabled"`
	SystemID    sql.NullInt64  `db:"system_id" json:"system_id"`
	TalkgroupID sql.NullInt64  `db:"talkgroup_id" json:"talkgroup_id"`
	Order       int64          `db:"order" json:"order"`
}

type Downstream struct {
	ID          int64          `db:"id" json:"id"`
	Url         string         `db:"url" json:"url"`
	ApiKey      string         `db:"api_key" json:"api_key"`
	SystemsJson sql.NullString `db:"systems_json" json:"systems_json"`
	Disabled    int64          `db:"disabled" json:"disabled"`
	Order       int64          `db:"order" json:"order"`
}

type Group struct {
	ID    int64  `db:"id" json:"id"`
	Label string `db:"label" json:"label"`
}

type Log struct {
	ID       int64  `db:"id" json:"id"`
	DateTime int64  `db:"date_time" json:"date_time"`
	Level    string `db:"level" json:"level"`
	Message  string `db:"message" json:"message"`
}

type PushSubscription struct {
	ID          int64          `db:"id" json:"id"`
	UserID      sql.NullInt64  `db:"user_id" json:"user_id"`
	SessionID   sql.NullString `db:"session_id" json:"session_id"`
	Endpoint    string         `db:"endpoint" json:"endpoint"`
	KeysJson    string         `db:"keys_json" json:"keys_json"`
	SystemsJson sql.NullString `db:"systems_json" json:"systems_json"`
	CreatedAt   int64          `db:"created_at" json:"created_at"`
}

type Setting struct {
	Key   string `db:"key" json:"key"`
	Value string `db:"value" json:"value"`
}

type SharedLink struct {
	ID        int64  `db:"id" json:"id"`
	CallID    int64  `db:"call_id" json:"call_id"`
	UserID    int64  `db:"user_id" json:"user_id"`
	Token     string `db:"token" json:"token"`
	CreatedAt int64  `db:"created_at" json:"created_at"`
}

type System struct {
	ID             int64          `db:"id" json:"id"`
	SystemID       int64          `db:"system_id" json:"system_id"`
	Label          string         `db:"label" json:"label"`
	AutoPopulate   int64          `db:"auto_populate" json:"auto_populate"`
	BlacklistsJson sql.NullString `db:"blacklists_json" json:"blacklists_json"`
	Led            sql.NullString `db:"led" json:"led"`
	Order          int64          `db:"order" json:"order"`
}

type Tag struct {
	ID    int64  `db:"id" json:"id"`
	Label string `db:"label" json:"label"`
}

type Talkgroup struct {
	ID          int64          `db:"id" json:"id"`
	SystemID    int64          `db:"system_id" json:"system_id"`
	TalkgroupID int64          `db:"talkgroup_id" json:"talkgroup_id"`
	Label       sql.NullString `db:"label" json:"label"`
	Name        sql.NullString `db:"name" json:"name"`
	Frequency   sql.NullInt64  `db:"frequency" json:"frequency"`
	Led         sql.NullString `db:"led" json:"led"`
	GroupID     sql.NullInt64  `db:"group_id" json:"group_id"`
	TagID       sql.NullInt64  `db:"tag_id" json:"tag_id"`
	Order       int64          `db:"order" json:"order"`
}

type Transcription struct {
	ID         int64          `db:"id" json:"id"`
	CallID     int64          `db:"call_id" json:"call_id"`
	Text       string         `db:"text" json:"text"`
	Language   sql.NullString `db:"language" json:"language"`
	Model      sql.NullString `db:"model" json:"model"`
	DurationMs sql.NullInt64  `db:"duration_ms" json:"duration_ms"`
	CreatedAt  int64          `db:"created_at" json:"created_at"`
}

type Unit struct {
	ID       int64          `db:"id" json:"id"`
	SystemID int64          `db:"system_id" json:"system_id"`
	UnitID   int64          `db:"unit_id" json:"unit_id"`
	Label    sql.NullString `db:"label" json:"label"`
	Order    int64          `db:"order" json:"order"`
}

type User struct {
	ID                 int64          `db:"id" json:"id"`
	Username           string         `db:"username" json:"username"`
	PasswordHash       string         `db:"password_hash" json:"-"`
	Role               string         `db:"role" json:"role"`
	Disabled           int64          `db:"disabled" json:"disabled"`
	SystemsJson        sql.NullString `db:"systems_json" json:"systems_json"`
	Expiration         sql.NullInt64  `db:"expiration" json:"expiration"`
	Limit              sql.NullInt64  `db:"limit" json:"limit"`
	PasswordNeedChange int64          `db:"password_need_change" json:"password_need_change"`
	CreatedAt          int64          `db:"created_at" json:"created_at"`
	UpdatedAt          int64          `db:"updated_at" json:"updated_at"`
}

type Webhook struct {
	ID          int64          `db:"id" json:"id"`
	Url         string         `db:"url" json:"url"`
	Type        string         `db:"type" json:"type"`
	Secret      sql.NullString `db:"secret" json:"secret"`
	SystemsJson sql.NullString `db:"systems_json" json:"systems_json"`
	Disabled    int64          `db:"disabled" json:"disabled"`
	Order       int64          `db:"order" json:"order"`
}
