// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: push_subscriptions.sql

package db

import (
	"context"
	"database/sql"
)

const createPushSubscription = `-- name: CreatePushSubscription :one
INSERT INTO push_subscriptions (
    user_id,
    session_id,
    endpoint,
    keys_json,
    systems_json,
    created_at
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6
) RETURNING id
`

type CreatePushSubscriptionParams struct {
	UserID      sql.NullInt64  `db:"user_id" json:"user_id"`
	SessionID   sql.NullString `db:"session_id" json:"session_id"`
	Endpoint    string         `db:"endpoint" json:"endpoint"`
	KeysJson    string         `db:"keys_json" json:"keys_json"`
	SystemsJson sql.NullString `db:"systems_json" json:"systems_json"`
	CreatedAt   int64          `db:"created_at" json:"created_at"`
}

func (q *Queries) CreatePushSubscription(ctx context.Context, arg CreatePushSubscriptionParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createPushSubscription,
		arg.UserID,
		arg.SessionID,
		arg.Endpoint,
		arg.KeysJson,
		arg.SystemsJson,
		arg.CreatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deletePushSubscription = `-- name: DeletePushSubscription :exec
DELETE FROM push_subscriptions WHERE id = ?
`

func (q *Queries) DeletePushSubscription(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deletePushSubscription, id)
	return err
}

const deletePushSubscriptionByEndpoint = `-- name: DeletePushSubscriptionByEndpoint :exec
DELETE FROM push_subscriptions WHERE endpoint = ?
`

func (q *Queries) DeletePushSubscriptionByEndpoint(ctx context.Context, endpoint string) error {
	_, err := q.db.ExecContext(ctx, deletePushSubscriptionByEndpoint, endpoint)
	return err
}

const getPushSubscription = `-- name: GetPushSubscription :one
SELECT id, user_id, session_id, endpoint, keys_json, systems_json, created_at FROM push_subscriptions WHERE id = ? LIMIT 1
`

func (q *Queries) GetPushSubscription(ctx context.Context, id int64) (PushSubscription, error) {
	row := q.db.QueryRowContext(ctx, getPushSubscription, id)
	var i PushSubscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SessionID,
		&i.Endpoint,
		&i.KeysJson,
		&i.SystemsJson,
		&i.CreatedAt,
	)
	return i, err
}

const listAllActivePushSubscriptions = `-- name: ListAllActivePushSubscriptions :many
SELECT id, user_id, session_id, endpoint, keys_json, systems_json, created_at FROM push_subscriptions ORDER BY created_at DESC
`

func (q *Queries) ListAllActivePushSubscriptions(ctx context.Context) ([]PushSubscription, error) {
	rows, err := q.db.QueryContext(ctx, listAllActivePushSubscriptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PushSubscription{}
	for rows.Next() {
		var i PushSubscription
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SessionID,
			&i.Endpoint,
			&i.KeysJson,
			&i.SystemsJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPushSubscriptionsByUser = `-- name: ListPushSubscriptionsByUser :many
SELECT id, user_id, session_id, endpoint, keys_json, systems_json, created_at FROM push_subscriptions WHERE user_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListPushSubscriptionsByUser(ctx context.Context, userID sql.NullInt64) ([]PushSubscription, error) {
	rows, err := q.db.QueryContext(ctx, listPushSubscriptionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PushSubscription{}
	for rows.Next() {
		var i PushSubscription
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SessionID,
			&i.Endpoint,
			&i.KeysJson,
			&i.SystemsJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
