// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CountCalls(ctx context.Context) (int64, error)
	CountCallsFiltered(ctx context.Context, arg CountCallsFilteredParams) (int64, error)
	CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (int64, error)
	CreateAccess(ctx context.Context, arg CreateAccessParams) (int64, error)
	CreateBookmark(ctx context.Context, arg CreateBookmarkParams) (int64, error)
	CreateCall(ctx context.Context, arg CreateCallParams) (int64, error)
	CreateDirwatch(ctx context.Context, arg CreateDirwatchParams) (int64, error)
	CreateDownstream(ctx context.Context, arg CreateDownstreamParams) (int64, error)
	CreateGroup(ctx context.Context, label string) (int64, error)
	CreateLog(ctx context.Context, arg CreateLogParams) error
	CreatePushSubscription(ctx context.Context, arg CreatePushSubscriptionParams) (int64, error)
	CreateSystem(ctx context.Context, arg CreateSystemParams) (int64, error)
	CreateTag(ctx context.Context, label string) (int64, error)
	CreateTalkgroup(ctx context.Context, arg CreateTalkgroupParams) (int64, error)
	CreateTranscription(ctx context.Context, arg CreateTranscriptionParams) (int64, error)
	CreateUnit(ctx context.Context, arg CreateUnitParams) (int64, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (int64, error)
	CreateWebhook(ctx context.Context, arg CreateWebhookParams) (int64, error)
	DeleteAPIKey(ctx context.Context, id int64) error
	DeleteAccess(ctx context.Context, id int64) error
	DeleteBookmark(ctx context.Context, id int64) error
	DeleteBookmarkByCallAndUser(ctx context.Context, arg DeleteBookmarkByCallAndUserParams) error
	DeleteCall(ctx context.Context, id int64) error
	DeleteCallBatch(ctx context.Context, id int64) error
	DeleteDirwatch(ctx context.Context, id int64) error
	DeleteDownstream(ctx context.Context, id int64) error
	DeleteGroup(ctx context.Context, id int64) error
	DeletePushSubscription(ctx context.Context, id int64) error
	DeletePushSubscriptionByEndpoint(ctx context.Context, endpoint string) error
	DeleteSetting(ctx context.Context, key string) error
	DeleteSystem(ctx context.Context, id int64) error
	DeleteTag(ctx context.Context, id int64) error
	DeleteTalkgroup(ctx context.Context, id int64) error
	DeleteTalkgroupsBySystem(ctx context.Context, systemID int64) error
	DeleteTranscription(ctx context.Context, id int64) error
	DeleteUnit(ctx context.Context, id int64) error
	DeleteUnitsBySystem(ctx context.Context, systemID int64) error
	DeleteUser(ctx context.Context, id int64) error
	DeleteWebhook(ctx context.Context, id int64) error
	GetAPIKey(ctx context.Context, id int64) (ApiKey, error)
	GetAPIKeyByKey(ctx context.Context, key string) (ApiKey, error)
	GetAccess(ctx context.Context, id int64) (Access, error)
	GetAccessByCode(ctx context.Context, code string) (Access, error)
	GetAppState(ctx context.Context) (AppState, error)
	GetBookmark(ctx context.Context, id int64) (Bookmark, error)
	GetCall(ctx context.Context, id int64) (GetCallRow, error)
	GetCallIDsOlderThan(ctx context.Context, dateTime int64) ([]GetCallIDsOlderThanRow, error)
	GetDirwatch(ctx context.Context, id int64) (Dirwatch, error)
	GetDownstream(ctx context.Context, id int64) (Downstream, error)
	GetGroup(ctx context.Context, id int64) (Group, error)
	GetLastCallForTalkgroup(ctx context.Context, arg GetLastCallForTalkgroupParams) (GetLastCallForTalkgroupRow, error)
	GetPushSubscription(ctx context.Context, id int64) (PushSubscription, error)
	GetSetting(ctx context.Context, key string) (Setting, error)
	GetSystem(ctx context.Context, id int64) (System, error)
	GetSystemBySystemID(ctx context.Context, systemID int64) (System, error)
	GetTag(ctx context.Context, id int64) (Tag, error)
	GetTalkgroup(ctx context.Context, id int64) (Talkgroup, error)
	GetTalkgroupBySystemAndTGID(ctx context.Context, arg GetTalkgroupBySystemAndTGIDParams) (Talkgroup, error)
	GetTranscription(ctx context.Context, id int64) (Transcription, error)
	GetTranscriptionByCallID(ctx context.Context, callID int64) (Transcription, error)
	GetUnit(ctx context.Context, id int64) (Unit, error)
	GetUnitBySystemAndUnitID(ctx context.Context, arg GetUnitBySystemAndUnitIDParams) (Unit, error)
	GetUser(ctx context.Context, id int64) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetWebhook(ctx context.Context, id int64) (Webhook, error)
	ListAPIKeys(ctx context.Context) ([]ApiKey, error)
	ListAccesses(ctx context.Context) ([]Access, error)
	ListActiveDirwatches(ctx context.Context) ([]Dirwatch, error)
	ListActiveDownstreams(ctx context.Context) ([]Downstream, error)
	ListActiveWebhooks(ctx context.Context) ([]Webhook, error)
	ListAllActivePushSubscriptions(ctx context.Context) ([]PushSubscription, error)
	ListAllTalkgroups(ctx context.Context) ([]Talkgroup, error)
	ListAllUnits(ctx context.Context) ([]Unit, error)
	ListBookmarksBySession(ctx context.Context, sessionID sql.NullString) ([]Bookmark, error)
	ListBookmarksByUser(ctx context.Context, userID sql.NullInt64) ([]Bookmark, error)
	ListCalls(ctx context.Context, arg ListCallsParams) ([]Call, error)
	ListCallsAsc(ctx context.Context, arg ListCallsAscParams) ([]Call, error)
	ListDirwatches(ctx context.Context) ([]Dirwatch, error)
	ListDownstreams(ctx context.Context) ([]Downstream, error)
	ListGroups(ctx context.Context) ([]Group, error)
	ListLogs(ctx context.Context) ([]Log, error)
	ListLogsByDateRange(ctx context.Context, arg ListLogsByDateRangeParams) ([]Log, error)
	ListLogsByDateRangeAndLevel(ctx context.Context, arg ListLogsByDateRangeAndLevelParams) ([]Log, error)
	ListPushSubscriptionsByUser(ctx context.Context, userID sql.NullInt64) ([]PushSubscription, error)
	ListSettings(ctx context.Context) ([]Setting, error)
	ListSystems(ctx context.Context) ([]System, error)
	ListTags(ctx context.Context) ([]Tag, error)
	ListTalkgroupsBySystem(ctx context.Context, systemID int64) ([]Talkgroup, error)
	ListUnitsBySystem(ctx context.Context, systemID int64) ([]Unit, error)
	ListUsers(ctx context.Context) ([]User, error)
	ListWebhooks(ctx context.Context) ([]Webhook, error)
	PruneCalls(ctx context.Context, dateTime int64) error
	PruneLogs(ctx context.Context, dateTime int64) error
	SetSetupComplete(ctx context.Context, setupComplete int64) error
	UpdateAPIKey(ctx context.Context, arg UpdateAPIKeyParams) error
	UpdateAccess(ctx context.Context, arg UpdateAccessParams) error
	UpdateDirwatch(ctx context.Context, arg UpdateDirwatchParams) error
	UpdateDownstream(ctx context.Context, arg UpdateDownstreamParams) error
	UpdateGroup(ctx context.Context, arg UpdateGroupParams) error
	UpdateSystem(ctx context.Context, arg UpdateSystemParams) error
	UpdateTag(ctx context.Context, arg UpdateTagParams) error
	UpdateTalkgroup(ctx context.Context, arg UpdateTalkgroupParams) error
	UpdateUnit(ctx context.Context, arg UpdateUnitParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateWebhook(ctx context.Context, arg UpdateWebhookParams) error
	UpsertSetting(ctx context.Context, arg UpsertSettingParams) error
	UpsertTalkgroup(ctx context.Context, arg UpsertTalkgroupParams) error
	UpsertUnit(ctx context.Context, arg UpsertUnitParams) error
}

var _ Querier = (*Queries)(nil)
