// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CountCalls(ctx context.Context) (int64, error)
	CountCallsFiltered(ctx context.Context, arg CountCallsFilteredParams) (int64, error)
	CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (int64, error)
	CreateBookmark(ctx context.Context, arg CreateBookmarkParams) (int64, error)
	CreateCall(ctx context.Context, arg CreateCallParams) (int64, error)
	CreateDirMonitor(ctx context.Context, arg CreateDirMonitorParams) (int64, error)
	CreateDownstream(ctx context.Context, arg CreateDownstreamParams) (int64, error)
	CreateGroup(ctx context.Context, label string) (int64, error)
	CreateLog(ctx context.Context, arg CreateLogParams) error
	CreatePushSubscription(ctx context.Context, arg CreatePushSubscriptionParams) (int64, error)
	CreateSharedLink(ctx context.Context, arg CreateSharedLinkParams) (SharedLink, error)
	CreateSystem(ctx context.Context, arg CreateSystemParams) (int64, error)
	CreateTag(ctx context.Context, label string) (int64, error)
	CreateTalkgroup(ctx context.Context, arg CreateTalkgroupParams) (int64, error)
	CreateTranscription(ctx context.Context, arg CreateTranscriptionParams) (int64, error)
	CreateUnit(ctx context.Context, arg CreateUnitParams) (int64, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (int64, error)
	CreateWebhook(ctx context.Context, arg CreateWebhookParams) (int64, error)
	DeleteAPIKey(ctx context.Context, id int64) error
	DeleteBookmark(ctx context.Context, id int64) error
	DeleteBookmarkByCallAndUser(ctx context.Context, arg DeleteBookmarkByCallAndUserParams) error
	DeleteCall(ctx context.Context, id int64) error
	DeleteCallBatch(ctx context.Context, id int64) error
	DeleteDirMonitor(ctx context.Context, id int64) error
	DeleteDownstream(ctx context.Context, id int64) error
	DeleteGroup(ctx context.Context, id int64) error
	DeletePushSubscription(ctx context.Context, id int64) error
	DeletePushSubscriptionByEndpoint(ctx context.Context, endpoint string) error
	DeleteSetting(ctx context.Context, key string) error
	DeleteSharedLink(ctx context.Context, id int64) error
	DeleteSharedLinkByCallID(ctx context.Context, callID int64) error
	DeleteSystem(ctx context.Context, id int64) error
	DeleteTag(ctx context.Context, id int64) error
	DeleteTalkgroup(ctx context.Context, id int64) error
	DeleteTalkgroupsBySystem(ctx context.Context, systemID int64) error
	DeleteTranscription(ctx context.Context, id int64) error
	DeleteUnit(ctx context.Context, id int64) error
	DeleteUnitsBySystem(ctx context.Context, systemID int64) error
	DeleteUser(ctx context.Context, id int64) error
	DeleteWebhook(ctx context.Context, id int64) error
	GetAPIKey(ctx context.Context, id int64) (ApiKey, error)
	GetAPIKeyByKey(ctx context.Context, key string) (ApiKey, error)
	// Returns aggregate stats: today's calls, this week's calls, total calls.
	GetActivityStats(ctx context.Context, arg GetActivityStatsParams) (GetActivityStatsRow, error)
	GetAppState(ctx context.Context) (AppState, error)
	GetBookmark(ctx context.Context, id int64) (Bookmark, error)
	GetBookmarkByCallAndUser(ctx context.Context, arg GetBookmarkByCallAndUserParams) (Bookmark, error)
	GetCall(ctx context.Context, id int64) (GetCallRow, error)
	GetCallIDsOlderThan(ctx context.Context, dateTime int64) ([]GetCallIDsOlderThanRow, error)
	// Returns call count per hour for the last 24 hours (24 rows, one per hour bucket).
	GetCallsPerHour(ctx context.Context, dateTime int64) ([]GetCallsPerHourRow, error)
	GetDirMonitor(ctx context.Context, id int64) (Dirmonitor, error)
	GetDownstream(ctx context.Context, id int64) (Downstream, error)
	GetGroup(ctx context.Context, id int64) (Group, error)
	GetGroupByLabel(ctx context.Context, label string) (Group, error)
	GetPushSubscription(ctx context.Context, id int64) (PushSubscription, error)
	GetSetting(ctx context.Context, key string) (Setting, error)
	GetSharedLinkByCallID(ctx context.Context, callID int64) (SharedLink, error)
	GetSharedLinkByToken(ctx context.Context, token string) (GetSharedLinkByTokenRow, error)
	GetSystem(ctx context.Context, id int64) (System, error)
	GetSystemByLabel(ctx context.Context, label string) (System, error)
	GetSystemBySystemID(ctx context.Context, systemID int64) (System, error)
	GetTag(ctx context.Context, id int64) (Tag, error)
	GetTagByLabel(ctx context.Context, label string) (Tag, error)
	GetTalkgroup(ctx context.Context, id int64) (Talkgroup, error)
	GetTalkgroupBySystemAndTGID(ctx context.Context, arg GetTalkgroupBySystemAndTGIDParams) (Talkgroup, error)
	// Returns top N busiest talkgroups (by call count) in a time range.
	GetTopTalkgroups(ctx context.Context, arg GetTopTalkgroupsParams) ([]GetTopTalkgroupsRow, error)
	GetTranscription(ctx context.Context, id int64) (Transcription, error)
	GetTranscriptionByCallID(ctx context.Context, callID int64) (Transcription, error)
	GetUnit(ctx context.Context, id int64) (Unit, error)
	GetUnitBySystemAndUnitID(ctx context.Context, arg GetUnitBySystemAndUnitIDParams) (Unit, error)
	GetUser(ctx context.Context, id int64) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetWebhook(ctx context.Context, id int64) (Webhook, error)
	HasCallAtTimestamp(ctx context.Context, arg HasCallAtTimestampParams) (int64, error)
	HasCallInTimeRange(ctx context.Context, arg HasCallInTimeRangeParams) (int64, error)
	ListAPIKeys(ctx context.Context) ([]ApiKey, error)
	ListActiveDirMonitors(ctx context.Context) ([]Dirmonitor, error)
	ListActiveDownstreams(ctx context.Context) ([]Downstream, error)
	ListActiveWebhooks(ctx context.Context) ([]Webhook, error)
	ListAllActivePushSubscriptions(ctx context.Context) ([]PushSubscription, error)
	ListAllTalkgroups(ctx context.Context) ([]Talkgroup, error)
	ListAllUnits(ctx context.Context) ([]Unit, error)
	ListBookmarkCallIDsByUser(ctx context.Context, userID sql.NullInt64) ([]int64, error)
	ListBookmarkCallsByUser(ctx context.Context, userID sql.NullInt64) ([]ListBookmarkCallsByUserRow, error)
	ListBookmarksBySession(ctx context.Context, sessionID sql.NullString) ([]Bookmark, error)
	ListBookmarksByUser(ctx context.Context, userID sql.NullInt64) ([]Bookmark, error)
	ListCalls(ctx context.Context, arg ListCallsParams) ([]Call, error)
	ListCallsAsc(ctx context.Context, arg ListCallsAscParams) ([]Call, error)
	ListDirMonitors(ctx context.Context) ([]Dirmonitor, error)
	ListDownstreams(ctx context.Context) ([]Downstream, error)
	ListGroups(ctx context.Context) ([]Group, error)
	ListLogs(ctx context.Context) ([]Log, error)
	ListLogsByDateRange(ctx context.Context, arg ListLogsByDateRangeParams) ([]Log, error)
	ListLogsByDateRangeAndLevel(ctx context.Context, arg ListLogsByDateRangeAndLevelParams) ([]Log, error)
	ListPushSubscriptionsByUser(ctx context.Context, userID sql.NullInt64) ([]PushSubscription, error)
	ListSettings(ctx context.Context) ([]Setting, error)
	ListSharedLinks(ctx context.Context) ([]ListSharedLinksRow, error)
	ListSystems(ctx context.Context) ([]System, error)
	ListTags(ctx context.Context) ([]Tag, error)
	ListTalkgroupsBySystem(ctx context.Context, systemID int64) ([]Talkgroup, error)
	ListUnitsBySystem(ctx context.Context, systemID int64) ([]Unit, error)
	ListUsers(ctx context.Context) ([]User, error)
	ListWebhooks(ctx context.Context) ([]Webhook, error)
	PruneCalls(ctx context.Context, dateTime int64) error
	PruneLogs(ctx context.Context, dateTime int64) error
	SetSetupComplete(ctx context.Context, setupComplete int64) error
	UpdateAPIKey(ctx context.Context, arg UpdateAPIKeyParams) error
	UpdateDirMonitor(ctx context.Context, arg UpdateDirMonitorParams) error
	UpdateDownstream(ctx context.Context, arg UpdateDownstreamParams) error
	UpdateGroup(ctx context.Context, arg UpdateGroupParams) error
	UpdateSystem(ctx context.Context, arg UpdateSystemParams) error
	UpdateTag(ctx context.Context, arg UpdateTagParams) error
	UpdateTalkgroup(ctx context.Context, arg UpdateTalkgroupParams) error
	UpdateUnit(ctx context.Context, arg UpdateUnitParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateWebhook(ctx context.Context, arg UpdateWebhookParams) error
	UpsertSetting(ctx context.Context, arg UpsertSettingParams) error
	UpsertTalkgroup(ctx context.Context, arg UpsertTalkgroupParams) error
	UpsertUnit(ctx context.Context, arg UpsertUnitParams) error
}

var _ Querier = (*Queries)(nil)
