// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: tr_instances.sql

package db

import (
	"context"
	"database/sql"
)

const createTRInstance = `-- name: CreateTRInstance :one
INSERT INTO tr_instances (
    label,
    instance_id,
    broker_url,
    base_topic,
    unit_topic,
    message_topic,
    username,
    password_enc,
    tls_skip_verify,
    qos,
    enabled,
    created_at,
    updated_at
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7,
    ?8,
    ?9,
    ?10,
    ?11,
    ?12,
    ?13
) RETURNING id, label, instance_id, broker_url, base_topic, unit_topic, message_topic, username, password_enc, tls_skip_verify, qos, enabled, created_at, updated_at, last_seen_at
`

type CreateTRInstanceParams struct {
	Label         string         `db:"label" json:"label"`
	InstanceID    string         `db:"instance_id" json:"instance_id"`
	BrokerUrl     string         `db:"broker_url" json:"broker_url"`
	BaseTopic     string         `db:"base_topic" json:"base_topic"`
	UnitTopic     sql.NullString `db:"unit_topic" json:"unit_topic"`
	MessageTopic  sql.NullString `db:"message_topic" json:"message_topic"`
	Username      sql.NullString `db:"username" json:"username"`
	PasswordEnc   sql.NullString `db:"password_enc" json:"password_enc"`
	TlsSkipVerify int64          `db:"tls_skip_verify" json:"tls_skip_verify"`
	Qos           int64          `db:"qos" json:"qos"`
	Enabled       int64          `db:"enabled" json:"enabled"`
	CreatedAt     int64          `db:"created_at" json:"created_at"`
	UpdatedAt     int64          `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreateTRInstance(ctx context.Context, arg CreateTRInstanceParams) (TrInstance, error) {
	row := q.db.QueryRowContext(ctx, createTRInstance,
		arg.Label,
		arg.InstanceID,
		arg.BrokerUrl,
		arg.BaseTopic,
		arg.UnitTopic,
		arg.MessageTopic,
		arg.Username,
		arg.PasswordEnc,
		arg.TlsSkipVerify,
		arg.Qos,
		arg.Enabled,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i TrInstance
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.InstanceID,
		&i.BrokerUrl,
		&i.BaseTopic,
		&i.UnitTopic,
		&i.MessageTopic,
		&i.Username,
		&i.PasswordEnc,
		&i.TlsSkipVerify,
		&i.Qos,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const deleteTRInstance = `-- name: DeleteTRInstance :exec
DELETE FROM tr_instances WHERE id = ?
`

func (q *Queries) DeleteTRInstance(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTRInstance, id)
	return err
}

const getTRInstance = `-- name: GetTRInstance :one
SELECT id, label, instance_id, broker_url, base_topic, unit_topic, message_topic, username, password_enc, tls_skip_verify, qos, enabled, created_at, updated_at, last_seen_at FROM tr_instances WHERE id = ? LIMIT 1
`

func (q *Queries) GetTRInstance(ctx context.Context, id int64) (TrInstance, error) {
	row := q.db.QueryRowContext(ctx, getTRInstance, id)
	var i TrInstance
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.InstanceID,
		&i.BrokerUrl,
		&i.BaseTopic,
		&i.UnitTopic,
		&i.MessageTopic,
		&i.Username,
		&i.PasswordEnc,
		&i.TlsSkipVerify,
		&i.Qos,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const getTRInstanceByLabel = `-- name: GetTRInstanceByLabel :one
SELECT id, label, instance_id, broker_url, base_topic, unit_topic, message_topic, username, password_enc, tls_skip_verify, qos, enabled, created_at, updated_at, last_seen_at FROM tr_instances WHERE label = ? LIMIT 1
`

func (q *Queries) GetTRInstanceByLabel(ctx context.Context, label string) (TrInstance, error) {
	row := q.db.QueryRowContext(ctx, getTRInstanceByLabel, label)
	var i TrInstance
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.InstanceID,
		&i.BrokerUrl,
		&i.BaseTopic,
		&i.UnitTopic,
		&i.MessageTopic,
		&i.Username,
		&i.PasswordEnc,
		&i.TlsSkipVerify,
		&i.Qos,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const listEnabledTRInstances = `-- name: ListEnabledTRInstances :many
SELECT id, label, instance_id, broker_url, base_topic, unit_topic, message_topic, username, password_enc, tls_skip_verify, qos, enabled, created_at, updated_at, last_seen_at FROM tr_instances WHERE enabled = 1 ORDER BY label ASC
`

func (q *Queries) ListEnabledTRInstances(ctx context.Context) ([]TrInstance, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledTRInstances)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TrInstance{}
	for rows.Next() {
		var i TrInstance
		if err := rows.Scan(
			&i.ID,
			&i.Label,
			&i.InstanceID,
			&i.BrokerUrl,
			&i.BaseTopic,
			&i.UnitTopic,
			&i.MessageTopic,
			&i.Username,
			&i.PasswordEnc,
			&i.TlsSkipVerify,
			&i.Qos,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTRInstances = `-- name: ListTRInstances :many
SELECT id, label, instance_id, broker_url, base_topic, unit_topic, message_topic, username, password_enc, tls_skip_verify, qos, enabled, created_at, updated_at, last_seen_at FROM tr_instances ORDER BY label ASC
`

func (q *Queries) ListTRInstances(ctx context.Context) ([]TrInstance, error) {
	rows, err := q.db.QueryContext(ctx, listTRInstances)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TrInstance{}
	for rows.Next() {
		var i TrInstance
		if err := rows.Scan(
			&i.ID,
			&i.Label,
			&i.InstanceID,
			&i.BrokerUrl,
			&i.BaseTopic,
			&i.UnitTopic,
			&i.MessageTopic,
			&i.Username,
			&i.PasswordEnc,
			&i.TlsSkipVerify,
			&i.Qos,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchTRInstanceLastSeen = `-- name: TouchTRInstanceLastSeen :exec
UPDATE tr_instances SET last_seen_at = ?1 WHERE id = ?2
`

type TouchTRInstanceLastSeenParams struct {
	LastSeenAt sql.NullInt64 `db:"last_seen_at" json:"last_seen_at"`
	ID         int64         `db:"id" json:"id"`
}

func (q *Queries) TouchTRInstanceLastSeen(ctx context.Context, arg TouchTRInstanceLastSeenParams) error {
	_, err := q.db.ExecContext(ctx, touchTRInstanceLastSeen, arg.LastSeenAt, arg.ID)
	return err
}

const updateTRInstance = `-- name: UpdateTRInstance :one
UPDATE tr_instances SET
    label           = ?1,
    instance_id     = ?2,
    broker_url      = ?3,
    base_topic      = ?4,
    unit_topic      = ?5,
    message_topic   = ?6,
    username        = ?7,
    password_enc    = ?8,
    tls_skip_verify = ?9,
    qos             = ?10,
    enabled         = ?11,
    updated_at      = ?12
WHERE id = ?13
RETURNING id, label, instance_id, broker_url, base_topic, unit_topic, message_topic, username, password_enc, tls_skip_verify, qos, enabled, created_at, updated_at, last_seen_at
`

type UpdateTRInstanceParams struct {
	Label         string         `db:"label" json:"label"`
	InstanceID    string         `db:"instance_id" json:"instance_id"`
	BrokerUrl     string         `db:"broker_url" json:"broker_url"`
	BaseTopic     string         `db:"base_topic" json:"base_topic"`
	UnitTopic     sql.NullString `db:"unit_topic" json:"unit_topic"`
	MessageTopic  sql.NullString `db:"message_topic" json:"message_topic"`
	Username      sql.NullString `db:"username" json:"username"`
	PasswordEnc   sql.NullString `db:"password_enc" json:"password_enc"`
	TlsSkipVerify int64          `db:"tls_skip_verify" json:"tls_skip_verify"`
	Qos           int64          `db:"qos" json:"qos"`
	Enabled       int64          `db:"enabled" json:"enabled"`
	UpdatedAt     int64          `db:"updated_at" json:"updated_at"`
	ID            int64          `db:"id" json:"id"`
}

func (q *Queries) UpdateTRInstance(ctx context.Context, arg UpdateTRInstanceParams) (TrInstance, error) {
	row := q.db.QueryRowContext(ctx, updateTRInstance,
		arg.Label,
		arg.InstanceID,
		arg.BrokerUrl,
		arg.BaseTopic,
		arg.UnitTopic,
		arg.MessageTopic,
		arg.Username,
		arg.PasswordEnc,
		arg.TlsSkipVerify,
		arg.Qos,
		arg.Enabled,
		arg.UpdatedAt,
		arg.ID,
	)
	var i TrInstance
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.InstanceID,
		&i.BrokerUrl,
		&i.BaseTopic,
		&i.UnitTopic,
		&i.MessageTopic,
		&i.Username,
		&i.PasswordEnc,
		&i.TlsSkipVerify,
		&i.Qos,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const updateTRInstancePassword = `-- name: UpdateTRInstancePassword :exec
UPDATE tr_instances SET
    password_enc = ?1,
    updated_at   = ?2
WHERE id = ?3
`

type UpdateTRInstancePasswordParams struct {
	PasswordEnc sql.NullString `db:"password_enc" json:"password_enc"`
	UpdatedAt   int64          `db:"updated_at" json:"updated_at"`
	ID          int64          `db:"id" json:"id"`
}

func (q *Queries) UpdateTRInstancePassword(ctx context.Context, arg UpdateTRInstancePasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateTRInstancePassword, arg.PasswordEnc, arg.UpdatedAt, arg.ID)
	return err
}
