// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: transcriptions.sql

package db

import (
	"context"
	"database/sql"
)

const createTranscription = `-- name: CreateTranscription :one
INSERT INTO transcriptions (
    call_id,
    text,
    language,
    model,
    duration_ms,
    created_at
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6
) RETURNING id
`

type CreateTranscriptionParams struct {
	CallID     int64          `db:"call_id" json:"call_id"`
	Text       string         `db:"text" json:"text"`
	Language   sql.NullString `db:"language" json:"language"`
	Model      sql.NullString `db:"model" json:"model"`
	DurationMs sql.NullInt64  `db:"duration_ms" json:"duration_ms"`
	CreatedAt  int64          `db:"created_at" json:"created_at"`
}

func (q *Queries) CreateTranscription(ctx context.Context, arg CreateTranscriptionParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createTranscription,
		arg.CallID,
		arg.Text,
		arg.Language,
		arg.Model,
		arg.DurationMs,
		arg.CreatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteTranscription = `-- name: DeleteTranscription :exec
DELETE FROM transcriptions WHERE id = ?
`

func (q *Queries) DeleteTranscription(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTranscription, id)
	return err
}

const getTranscription = `-- name: GetTranscription :one
SELECT id, call_id, text, language, model, duration_ms, created_at FROM transcriptions WHERE id = ? LIMIT 1
`

func (q *Queries) GetTranscription(ctx context.Context, id int64) (Transcription, error) {
	row := q.db.QueryRowContext(ctx, getTranscription, id)
	var i Transcription
	err := row.Scan(
		&i.ID,
		&i.CallID,
		&i.Text,
		&i.Language,
		&i.Model,
		&i.DurationMs,
		&i.CreatedAt,
	)
	return i, err
}

const getTranscriptionByCallID = `-- name: GetTranscriptionByCallID :one
SELECT id, call_id, text, language, model, duration_ms, created_at FROM transcriptions WHERE call_id = ? LIMIT 1
`

func (q *Queries) GetTranscriptionByCallID(ctx context.Context, callID int64) (Transcription, error) {
	row := q.db.QueryRowContext(ctx, getTranscriptionByCallID, callID)
	var i Transcription
	err := row.Scan(
		&i.ID,
		&i.CallID,
		&i.Text,
		&i.Language,
		&i.Model,
		&i.DurationMs,
		&i.CreatedAt,
	)
	return i, err
}
