// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: transcriptions.sql

package db

import (
	"context"
	"database/sql"
)

const countTranscriptions = `-- name: CountTranscriptions :one
SELECT COUNT(*) FROM transcriptions
`

func (q *Queries) CountTranscriptions(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTranscriptions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTranscription = `-- name: CreateTranscription :one
INSERT INTO transcriptions (
    call_id,
    text,
    segments,
    language,
    model,
    duration_ms,
    created_at
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7
) RETURNING id
`

type CreateTranscriptionParams struct {
	CallID     int64          `db:"call_id" json:"call_id"`
	Text       string         `db:"text" json:"text"`
	Segments   sql.NullString `db:"segments" json:"segments"`
	Language   sql.NullString `db:"language" json:"language"`
	Model      sql.NullString `db:"model" json:"model"`
	DurationMs sql.NullInt64  `db:"duration_ms" json:"duration_ms"`
	CreatedAt  int64          `db:"created_at" json:"created_at"`
}

func (q *Queries) CreateTranscription(ctx context.Context, arg CreateTranscriptionParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createTranscription,
		arg.CallID,
		arg.Text,
		arg.Segments,
		arg.Language,
		arg.Model,
		arg.DurationMs,
		arg.CreatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteTranscription = `-- name: DeleteTranscription :exec
DELETE FROM transcriptions WHERE id = ?
`

func (q *Queries) DeleteTranscription(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTranscription, id)
	return err
}

const deleteTranscriptionByCallID = `-- name: DeleteTranscriptionByCallID :exec
DELETE FROM transcriptions WHERE call_id = ?
`

func (q *Queries) DeleteTranscriptionByCallID(ctx context.Context, callID int64) error {
	_, err := q.db.ExecContext(ctx, deleteTranscriptionByCallID, callID)
	return err
}

const getTranscription = `-- name: GetTranscription :one
SELECT id, call_id, text, segments, language, model, duration_ms, created_at FROM transcriptions WHERE id = ? LIMIT 1
`

func (q *Queries) GetTranscription(ctx context.Context, id int64) (Transcription, error) {
	row := q.db.QueryRowContext(ctx, getTranscription, id)
	var i Transcription
	err := row.Scan(
		&i.ID,
		&i.CallID,
		&i.Text,
		&i.Segments,
		&i.Language,
		&i.Model,
		&i.DurationMs,
		&i.CreatedAt,
	)
	return i, err
}

const getTranscriptionByCallID = `-- name: GetTranscriptionByCallID :one
SELECT id, call_id, text, segments, language, model, duration_ms, created_at FROM transcriptions WHERE call_id = ? LIMIT 1
`

func (q *Queries) GetTranscriptionByCallID(ctx context.Context, callID int64) (Transcription, error) {
	row := q.db.QueryRowContext(ctx, getTranscriptionByCallID, callID)
	var i Transcription
	err := row.Scan(
		&i.ID,
		&i.CallID,
		&i.Text,
		&i.Segments,
		&i.Language,
		&i.Model,
		&i.DurationMs,
		&i.CreatedAt,
	)
	return i, err
}

const searchTranscriptions = `-- name: SearchTranscriptions :many
SELECT t.id, t.call_id, t.text, t.segments, t.language, t.model,
       t.duration_ms, t.created_at,
       c.date_time, c.system_id, c.talkgroup_id
FROM transcriptions t
JOIN calls c ON c.id = t.call_id
WHERE t.text LIKE '%' || ?1 || '%'
ORDER BY c.date_time DESC
LIMIT ?3 OFFSET ?2
`

type SearchTranscriptionsParams struct {
	Query sql.NullString `db:"query" json:"query"`
	Off   int64          `db:"off" json:"off"`
	Lim   int64          `db:"lim" json:"lim"`
}

type SearchTranscriptionsRow struct {
	ID          int64          `db:"id" json:"id"`
	CallID      int64          `db:"call_id" json:"call_id"`
	Text        string         `db:"text" json:"text"`
	Segments    sql.NullString `db:"segments" json:"segments"`
	Language    sql.NullString `db:"language" json:"language"`
	Model       sql.NullString `db:"model" json:"model"`
	DurationMs  sql.NullInt64  `db:"duration_ms" json:"duration_ms"`
	CreatedAt   int64          `db:"created_at" json:"created_at"`
	DateTime    int64          `db:"date_time" json:"date_time"`
	SystemID    int64          `db:"system_id" json:"system_id"`
	TalkgroupID sql.NullInt64  `db:"talkgroup_id" json:"talkgroup_id"`
}

func (q *Queries) SearchTranscriptions(ctx context.Context, arg SearchTranscriptionsParams) ([]SearchTranscriptionsRow, error) {
	rows, err := q.db.QueryContext(ctx, searchTranscriptions, arg.Query, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchTranscriptionsRow{}
	for rows.Next() {
		var i SearchTranscriptionsRow
		if err := rows.Scan(
			&i.ID,
			&i.CallID,
			&i.Text,
			&i.Segments,
			&i.Language,
			&i.Model,
			&i.DurationMs,
			&i.CreatedAt,
			&i.DateTime,
			&i.SystemID,
			&i.TalkgroupID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const transcriptionStats = `-- name: TranscriptionStats :one
SELECT
    COUNT(*) AS total,
    COALESCE(AVG(duration_ms), 0) AS avg_duration_ms,
    COALESCE(MIN(duration_ms), 0) AS min_duration_ms,
    COALESCE(MAX(duration_ms), 0) AS max_duration_ms,
    COUNT(CASE WHEN created_at >= ?1 THEN 1 END) AS recent_count
FROM transcriptions
`

type TranscriptionStatsRow struct {
	Total         int64       `db:"total" json:"total"`
	AvgDurationMs interface{} `db:"avg_duration_ms" json:"avg_duration_ms"`
	MinDurationMs interface{} `db:"min_duration_ms" json:"min_duration_ms"`
	MaxDurationMs interface{} `db:"max_duration_ms" json:"max_duration_ms"`
	RecentCount   int64       `db:"recent_count" json:"recent_count"`
}

func (q *Queries) TranscriptionStats(ctx context.Context, since int64) (TranscriptionStatsRow, error) {
	row := q.db.QueryRowContext(ctx, transcriptionStats, since)
	var i TranscriptionStatsRow
	err := row.Scan(
		&i.Total,
		&i.AvgDurationMs,
		&i.MinDurationMs,
		&i.MaxDurationMs,
		&i.RecentCount,
	)
	return i, err
}

const transcriptionsByLanguage = `-- name: TranscriptionsByLanguage :many
SELECT COALESCE(language, 'unknown') AS lang, COUNT(*) AS cnt
FROM transcriptions
GROUP BY language
ORDER BY cnt DESC
LIMIT 10
`

type TranscriptionsByLanguageRow struct {
	Lang string `db:"lang" json:"lang"`
	Cnt  int64  `db:"cnt" json:"cnt"`
}

func (q *Queries) TranscriptionsByLanguage(ctx context.Context) ([]TranscriptionsByLanguageRow, error) {
	rows, err := q.db.QueryContext(ctx, transcriptionsByLanguage)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TranscriptionsByLanguageRow{}
	for rows.Next() {
		var i TranscriptionsByLanguageRow
		if err := rows.Scan(&i.Lang, &i.Cnt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const transcriptionsByModel = `-- name: TranscriptionsByModel :many
SELECT COALESCE(model, 'unknown') AS model_name, COUNT(*) AS cnt
FROM transcriptions
GROUP BY model
ORDER BY cnt DESC
LIMIT 10
`

type TranscriptionsByModelRow struct {
	ModelName string `db:"model_name" json:"model_name"`
	Cnt       int64  `db:"cnt" json:"cnt"`
}

func (q *Queries) TranscriptionsByModel(ctx context.Context) ([]TranscriptionsByModelRow, error) {
	rows, err := q.db.QueryContext(ctx, transcriptionsByModel)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TranscriptionsByModelRow{}
	for rows.Next() {
		var i TranscriptionsByModelRow
		if err := rows.Scan(&i.ModelName, &i.Cnt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
