// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: units.sql

package db

import (
	"context"
	"database/sql"
)

const createUnit = `-- name: CreateUnit :one
INSERT INTO units (
    system_id,
    unit_id,
    label,
    "order"
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4
) RETURNING id
`

type CreateUnitParams struct {
	SystemID int64          `db:"system_id" json:"system_id"`
	UnitID   int64          `db:"unit_id" json:"unit_id"`
	Label    sql.NullString `db:"label" json:"label"`
	Order    int64          `db:"order" json:"order"`
}

func (q *Queries) CreateUnit(ctx context.Context, arg CreateUnitParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createUnit,
		arg.SystemID,
		arg.UnitID,
		arg.Label,
		arg.Order,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteUnit = `-- name: DeleteUnit :exec
DELETE FROM units WHERE id = ?
`

func (q *Queries) DeleteUnit(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteUnit, id)
	return err
}

const deleteUnitsBySystem = `-- name: DeleteUnitsBySystem :exec
DELETE FROM units WHERE system_id = ?
`

func (q *Queries) DeleteUnitsBySystem(ctx context.Context, systemID int64) error {
	_, err := q.db.ExecContext(ctx, deleteUnitsBySystem, systemID)
	return err
}

const getUnit = `-- name: GetUnit :one
SELECT id, system_id, unit_id, label, "order" FROM units WHERE id = ? LIMIT 1
`

func (q *Queries) GetUnit(ctx context.Context, id int64) (Unit, error) {
	row := q.db.QueryRowContext(ctx, getUnit, id)
	var i Unit
	err := row.Scan(
		&i.ID,
		&i.SystemID,
		&i.UnitID,
		&i.Label,
		&i.Order,
	)
	return i, err
}

const getUnitBySystemAndUnitID = `-- name: GetUnitBySystemAndUnitID :one
SELECT id, system_id, unit_id, label, "order" FROM units
WHERE system_id = ? AND unit_id = ?
LIMIT 1
`

type GetUnitBySystemAndUnitIDParams struct {
	SystemID int64 `db:"system_id" json:"system_id"`
	UnitID   int64 `db:"unit_id" json:"unit_id"`
}

func (q *Queries) GetUnitBySystemAndUnitID(ctx context.Context, arg GetUnitBySystemAndUnitIDParams) (Unit, error) {
	row := q.db.QueryRowContext(ctx, getUnitBySystemAndUnitID, arg.SystemID, arg.UnitID)
	var i Unit
	err := row.Scan(
		&i.ID,
		&i.SystemID,
		&i.UnitID,
		&i.Label,
		&i.Order,
	)
	return i, err
}

const listAllUnits = `-- name: ListAllUnits :many
SELECT id, system_id, unit_id, label, "order" FROM units ORDER BY system_id ASC, "order" ASC, unit_id ASC
`

func (q *Queries) ListAllUnits(ctx context.Context) ([]Unit, error) {
	rows, err := q.db.QueryContext(ctx, listAllUnits)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Unit{}
	for rows.Next() {
		var i Unit
		if err := rows.Scan(
			&i.ID,
			&i.SystemID,
			&i.UnitID,
			&i.Label,
			&i.Order,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnitsBySystem = `-- name: ListUnitsBySystem :many
SELECT id, system_id, unit_id, label, "order" FROM units
WHERE system_id = ?
ORDER BY "order" ASC, unit_id ASC
`

func (q *Queries) ListUnitsBySystem(ctx context.Context, systemID int64) ([]Unit, error) {
	rows, err := q.db.QueryContext(ctx, listUnitsBySystem, systemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Unit{}
	for rows.Next() {
		var i Unit
		if err := rows.Scan(
			&i.ID,
			&i.SystemID,
			&i.UnitID,
			&i.Label,
			&i.Order,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUnit = `-- name: UpdateUnit :exec
UPDATE units SET
    unit_id = ?1,
    label   = ?2,
    "order" = ?3
WHERE id = ?4
`

type UpdateUnitParams struct {
	UnitID int64          `db:"unit_id" json:"unit_id"`
	Label  sql.NullString `db:"label" json:"label"`
	Order  int64          `db:"order" json:"order"`
	ID     int64          `db:"id" json:"id"`
}

func (q *Queries) UpdateUnit(ctx context.Context, arg UpdateUnitParams) error {
	_, err := q.db.ExecContext(ctx, updateUnit,
		arg.UnitID,
		arg.Label,
		arg.Order,
		arg.ID,
	)
	return err
}

const upsertUnit = `-- name: UpsertUnit :exec
INSERT OR IGNORE INTO units (system_id, unit_id, label, "order")
VALUES (?1, ?2, ?3, ?4)
`

type UpsertUnitParams struct {
	SystemID int64          `db:"system_id" json:"system_id"`
	UnitID   int64          `db:"unit_id" json:"unit_id"`
	Label    sql.NullString `db:"label" json:"label"`
	Order    int64          `db:"order" json:"order"`
}

func (q *Queries) UpsertUnit(ctx context.Context, arg UpsertUnitParams) error {
	_, err := q.db.ExecContext(ctx, upsertUnit,
		arg.SystemID,
		arg.UnitID,
		arg.Label,
		arg.Order,
	)
	return err
}
