// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: webhooks.sql

package db

import (
	"context"
	"database/sql"
)

const createWebhook = `-- name: CreateWebhook :one
INSERT INTO webhooks (
    url,
    type,
    secret,
    systems_json,
    disabled,
    "order"
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6
) RETURNING id
`

type CreateWebhookParams struct {
	Url         string         `db:"url" json:"url"`
	Type        string         `db:"type" json:"type"`
	Secret      sql.NullString `db:"secret" json:"secret"`
	SystemsJson sql.NullString `db:"systems_json" json:"systems_json"`
	Disabled    int64          `db:"disabled" json:"disabled"`
	Order       int64          `db:"order" json:"order"`
}

func (q *Queries) CreateWebhook(ctx context.Context, arg CreateWebhookParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createWebhook,
		arg.Url,
		arg.Type,
		arg.Secret,
		arg.SystemsJson,
		arg.Disabled,
		arg.Order,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteWebhook = `-- name: DeleteWebhook :exec
DELETE FROM webhooks WHERE id = ?
`

func (q *Queries) DeleteWebhook(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteWebhook, id)
	return err
}

const getWebhook = `-- name: GetWebhook :one
SELECT id, url, type, secret, systems_json, disabled, "order" FROM webhooks WHERE id = ? LIMIT 1
`

func (q *Queries) GetWebhook(ctx context.Context, id int64) (Webhook, error) {
	row := q.db.QueryRowContext(ctx, getWebhook, id)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Type,
		&i.Secret,
		&i.SystemsJson,
		&i.Disabled,
		&i.Order,
	)
	return i, err
}

const listActiveWebhooks = `-- name: ListActiveWebhooks :many
SELECT id, url, type, secret, systems_json, disabled, "order" FROM webhooks WHERE disabled = 0 ORDER BY "order" ASC, id ASC
`

func (q *Queries) ListActiveWebhooks(ctx context.Context) ([]Webhook, error) {
	rows, err := q.db.QueryContext(ctx, listActiveWebhooks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Webhook{}
	for rows.Next() {
		var i Webhook
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Type,
			&i.Secret,
			&i.SystemsJson,
			&i.Disabled,
			&i.Order,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhooks = `-- name: ListWebhooks :many
SELECT id, url, type, secret, systems_json, disabled, "order" FROM webhooks ORDER BY "order" ASC, id ASC
`

func (q *Queries) ListWebhooks(ctx context.Context) ([]Webhook, error) {
	rows, err := q.db.QueryContext(ctx, listWebhooks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Webhook{}
	for rows.Next() {
		var i Webhook
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Type,
			&i.Secret,
			&i.SystemsJson,
			&i.Disabled,
			&i.Order,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWebhook = `-- name: UpdateWebhook :exec
UPDATE webhooks SET
    url          = ?1,
    type         = ?2,
    secret       = ?3,
    systems_json = ?4,
    disabled     = ?5,
    "order"      = ?6
WHERE id = ?7
`

type UpdateWebhookParams struct {
	Url         string         `db:"url" json:"url"`
	Type        string         `db:"type" json:"type"`
	Secret      sql.NullString `db:"secret" json:"secret"`
	SystemsJson sql.NullString `db:"systems_json" json:"systems_json"`
	Disabled    int64          `db:"disabled" json:"disabled"`
	Order       int64          `db:"order" json:"order"`
	ID          int64          `db:"id" json:"id"`
}

func (q *Queries) UpdateWebhook(ctx context.Context, arg UpdateWebhookParams) error {
	_, err := q.db.ExecContext(ctx, updateWebhook,
		arg.Url,
		arg.Type,
		arg.Secret,
		arg.SystemsJson,
		arg.Disabled,
		arg.Order,
		arg.ID,
	)
	return err
}
